Spot check argo db for data
sul-dlss/argo pull request #2240
Opened 2020-09-01 17:41 UTC by tallenaz

## Why was this change made?

In addition to the okcomputer db schema check, we want to check for data loss. This is adapted from similar approaches in sul-pub and prescat

## How was this change tested?

Deployed to stage, and it works as expected.

## Which documentation and/or configurations were updated?

DevOpsDocs edits forthcoming.

2020-09-01 17:54 UTC, jcoyne commented
Has this sort of failure ever occurred? This seems like a strangely specific failure mode we're checking for.

2020-09-01 18:42 UTC, tallenaz commented
Not to my knowledge in argo. This sort of check does seem pretty important for cap and prescat. And we do want to be able to check for data loss where it's appropriate. Do we care, then, if these tables in argo lose data?

2020-09-02 01:41 UTC, jcoyne commented
@tallenaz yes, we care if data is lost, but this check doesn't check for that, it checks that these tables have at least one row in them.  That would be only a subset of the cases of data loss.  I think this is such a rare and catastrophic case to be not worth bothering checking for.  Furthermore, I don't think we care about most of these tables.  They are mostly blacklight builtins that we aren't using in Argo.

2020-09-02 16:01 UTC, tallenaz commented
We agree that we care about data loss, and we agree that this checks for a subset of cases of data loss. In my view, that makes this a case of "something is better than nothing". But it sounds like you have something better in mind, which I'd be happy to draw from. So I'd like to ask which tables in argo we care about, and how you think I could approach checking for a more central case or set of cases of data loss.

2020-09-03 02:02 UTC, jcoyne commented
@tallenaz This approach is like checking the office for tigers.  Yes, we don't want tigers in the office, but this is such an unusual occurrence, it's not something we bother doing.

2020-09-03 17:33 UTC, tallenaz commented
We agree this is a check for a catastrophic situation, but we disagree that this is a silly thing to be prepared for. Substitute earthquakes for tigers, for example.

2020-09-04 01:49 UTC, jcoyne commented
@tallenaz my point about about this being catastrophic (all the data is gone) is that we'd notice this through other means (honeybadger and user reports) and Nagios wouldn't be all that helpful.  Subtle data loss is more pernicious and we maybe wouldn't have another way to detect it.

2020-09-04 02:02 UTC, jcoyne commented on config/initializers/okcomputer.rb
> +      Search,
In the case of searches, this is okay to not have any. In fact they are supposed to be cleared out periodically: https://github.com/projectblacklight/blacklight/blob/91d5e6fb1fe8589262c3b86c0e5a2b5963e1f431/lib/railties/blacklight.rake#L5-L7

2020-09-04 02:04 UTC, jcoyne commented on config/initializers/okcomputer.rb
> +      Bookmark,
We don't use bookmarks:
```
 Bookmark.count
   (1.1ms)  SELECT COUNT(*) FROM `bookmarks`
=> 0
```

2020-09-14 16:23 UTC, tallenaz commented
Understood. Having some level of coverage through nagios is what ops is aiming for, even if it wouldn't be all that. I tacked on a commit addressing the last two comments.

2020-09-14 18:09 UTC, jcoyne approved these changes

2020-09-14 18:10 UTC, jcoyne requested changes

2020-09-14 18:10 UTC, jcoyne commented on config/initializers/okcomputer.rb
> +  rescue ActiveRecord::RecordNotFound
How do we ever get into here?

2020-09-14 18:20 UTC, jcoyne approved these changes

2020-10-30 11:46 UTC, merged