Decouple collection membership form from Fedora 3
sul-dlss/argo pull request #2412
Opened 2021-03-01 19:45 UTC by jcoyne

## Why was this change made?

Fixes #2399

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-03-01 19:47 UTC, jcoyne commented on app/helpers/value_helper.rb
> -    Honeybadger.notify("No title found in descMetadata for collection #{obj.pid}")
The last occurance of this was two years ago, so it's not something we're hitting anymore: https://app.honeybadger.io/projects/49894/faults/45409599

2021-03-08 17:23 UTC, aaron-collier requested changes

2021-03-08 17:23 UTC, aaron-collier commented on app/controllers/items_controller.rb
> +                                                                                     collection_id: col.id,
Should this be `collection.id`?

2021-03-08 21:51 UTC, jcoyne commented on app/controllers/items_controller.rb
> +                                                                                     collection_id: col.id,
Thank you. good catch!

2021-03-09 16:28 UTC, aaron-collier approved these changes

2021-03-09 16:28 UTC, merged