guard against republushing objects that have not been published
sul-dlss/argo pull request #2477
Opened 2021-03-11 20:15 UTC by peetucket

## Why was this change made?

Fixes #2384 

- before allowing a bulk action that republishes or releases object (which also would result in a publish), confirm that the object has actually been published before and abort if not
- rename the publish check route used by the "Republish" blue button to match what it does

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-03-11 20:16 UTC, peetucket commented on app/presenters/buttons_presenter.rb
> +           :dor_republish_path,
`dor_path` is not very descriptive since this is actually the republish path

2021-03-11 20:16 UTC, peetucket commented on config/routes.rb
> +    match 'republish/:pid', action: :republish, as: 'republish', via: %i[get post]
as noted above, `dor_path` is not very descriptive since this is actually the republish path

2021-03-11 20:43 UTC, jcoyne requested changes
Shouldn't this guard be in the dor-services-app API where it lets us "publish"?

2021-03-11 22:08 UTC, peetucket commented
> Shouldn't this guard be in the dor-services-app API where it lets us "publish"?

like here https://github.com/sul-dlss/dor-services-app/blob/main/app/jobs/publish_job.rb#L12  or here https://github.com/sul-dlss/dor-services-app/blob/main/app/controllers/objects_controller.rb#L90 ?

I guess if we do it in the controller, we could return an http status that indicated it didn't happen?  Not sure what the implications of that would be for consumers

2021-03-12 01:04 UTC, jcoyne commented
Yes, exactly. And that would prevent this from happening for any other API user.

2021-03-12 19:13 UTC, peetucket commented on spec/jobs/release_object_job_spec.rb
>  RSpec.describe ReleaseObjectJob do
Note that the tests changed a lot less that it appears from the diffs.  I basically added two separate contexts: 'with already published objects' and 'when objects have never been published'.  The `Dor::Workflow::Client` instance then mocks the return value to verify the publish doesn't happen.  The nesting of the existing tests in a new context block and the addition of the new mock for `Dor::Workflow::Client` resulted in a messy diff.  The end state is really just a few new tests.

2021-03-12 19:15 UTC, peetucket commented
The failed test above is the flappy `spec/features/item_registration_spec.rb` spec

2021-03-12 21:48 UTC, jcoyne approved these changes

2021-03-12 21:49 UTC, merged