WIP: Remove the dor-services dependency
sul-dlss/argo pull request #2596
Opened 2021-03-27 03:53 UTC by jcoyne

## Why was this change made?

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-04-05 21:36 UTC, mjgiarlo approved these changes

2021-04-05 21:37 UTC, jmartin-sul commented on Gemfile
> -gem 'dor-services', '~> 9.6'
🎉

2021-04-05 21:41 UTC, jmartin-sul approved these changes

2021-04-05 22:06 UTC, aaron-collier requested changes
Dropping a request changes just to hold this until testing complete.

2021-04-06 00:03 UTC, aaron-collier approved these changes

2021-04-06 00:03 UTC, merged