Import xml prettify from dor-services
sul-dlss/argo pull request #2604
Opened 2021-03-29 05:27 UTC by jcoyne

## Why was this change made?

This previously was a monkey-patch on Nokogiri::XML.  This helps us decouple from dor-services

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-03-29 19:15 UTC, ndushay commented
Does this require Andrew review??

2021-03-29 19:15 UTC, ndushay requested changes
marking as request changes to note that this may require andrew review ... not sure.

2021-04-02 19:13 UTC, andrewjbtw commented
Is this what displays the datastream and workflow XML display modals? I think it should be ok to merge but I'll be sure to look at those displays on stage when I review.

2021-04-02 20:41 UTC, ndushay approved these changes
as long as Andrew is happy, I'm happy.

2021-04-02 20:42 UTC, merged