[HOLD] Do not allow Collections to have CDL rights
sul-dlss/argo pull request #2634
Opened 2021-04-02 22:08 UTC by jcoyne

I'm waiting for Andrew to give feedback on this. 

## Why was this change made?
We previously had 3 lists of rights.  I think we only need one for collections and one for DROs.  The collections are different in that they may not have CDL access.

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-04-21 22:37 UTC, mjgiarlo approved these changes

2021-04-21 23:09 UTC, justinlittman requested changes
So I think this is handled by https://github.com/sul-dlss/argo/pull/2692, which fixes all of the rights options for collections, not just CDL. Let's discuss to see if this PR is necessary.

2021-04-21 23:25 UTC, jcoyne commented
@justinlittman I'm fine with #2692 going first, but I really want to excise DEFAULT_RIGHTS_OPTIONS as it's confusing. I don't know if you want to add that to your PR or we do that here.

2021-04-27 15:21 UTC, justinlittman approved these changes

2021-04-27 23:19 UTC, aaron-collier approved these changes

2021-04-27 23:20 UTC, merged