[HOLD] Adds manage embargo bulk action.
sul-dlss/argo pull request #2677
Opened 2021-04-15 12:16 UTC by justinlittman

closes #2671

## Why was this change made?
Support embargo management from Argo.

## How was this change tested?
Unit, QA

## Which documentation and/or configurations were updated?
NA

2021-04-15 12:16 UTC, justinlittman commented
Awaiting further clarification of requirements for embargo rights.

2021-04-28 18:53 UTC, justinlittman commented
Tested on QA by @andrewjbtw

2021-04-28 21:44 UTC, jcoyne commented on app/jobs/manage_embargoes_job.rb
> +        # ItemChangeSet.new(cocina_object).validate(changes).save_model unless changes.empty?
cruft?

2021-04-28 21:45 UTC, jcoyne requested changes

2021-04-28 21:45 UTC, jcoyne commented on app/jobs/manage_embargoes_job.rb
> +        change_set.save_model
You should call `save` here, `save_model` is an internal method called by save.

2021-04-29 12:35 UTC, jcoyne approved these changes

2021-04-29 12:36 UTC, merged