show workflow errors on item page
sul-dlss/argo pull request #3056
Opened 2022-02-02 21:01 UTC by peetucket

## Why was this change made?

Fixes #3027 - show workflow errors in alert dialog box on item page

## How was this change tested?

Localhost browser, existing tests

## Which documentation and/or configurations were updated?

2022-02-02 21:11 UTC, peetucket commented on app/controllers/catalog_controller.rb
if Solr document contains workflow errors, use the existing helper method to add them to the error flash

2022-02-02 21:11 UTC, peetucket commented on app/models/solr_document.rb
this is the field that contains Workflow errors in solr

2022-02-02 21:12 UTC, peetucket commented on app/views/layouts/blacklight/base.html.erb
there may be a better way to do this...basically, we don't want to render the flash messages in the layout if we are on detail page, as that is handled in the components (so they can be rendered in a different location instead)

2022-02-02 22:03 UTC, jcoyne requested changes

2022-02-02 22:05 UTC, jcoyne commented on app/views/layouts/blacklight/base.html.erb
> +    <%= render partial: 'shared/flash_msg', layout: 'shared/flash_messages' unless params[:id] && current_page?(solr_document_path)%>
please revert this.  This box is not for all the messages, only the message about the workflow error state.

2022-02-02 22:18 UTC, jcoyne commented on app/components/show/admin_policy_component.html.erb
> +<%= render partial: 'shared/flash_msg', layout: 'shared/flash_messages' %>
that is:
```ruby
  field_config =  blacklight_config.show_fields_for(:show).fetch(SolrDocument::FIELD_WORKFLOW_ERRORS)
  Blacklight::FieldPresenter.new(self, @solr_document, field_config).render
 ```

2022-02-03 00:01 UTC, peetucket commented
Ok, switched from flash to a new workflow error view component ... render component in the correct place in the detail pages.  All flash messages and locations left untouched.

2022-02-03 01:01 UTC, jcoyne approved these changes

2022-02-03 01:01 UTC, merged