fix bug where tags were not making it during registration
sul-dlss/argo pull request #3654
Opened 2022-05-04 23:07 UTC by peetucket

## Why was this change made? 🤔

Fixes #3650 - tags were not making it the object because the params being sent by javascript was "tag" and the params expected by the server where "tags"...normalized to "tags" , which makes more sense.

## How was this change tested? 🤨

Localhost browser.  Started working on a test to verify tags make it all the way through, but that might take longer...so this gets the bug fix out now.

2022-05-04 23:08 UTC, peetucket commented on app/javascript/registration/register.js
> +    // Grab list of tags from the form
it's not rejecting blanks anymore!  they get rejected on the server now

2022-05-05 01:28 UTC, jcoyne requested changes
Can you write a feature spec for this? We should be able to register an item with tags and show them on the page.

2022-05-05 17:43 UTC, jcoyne approved these changes

2022-05-05 17:43 UTC, jcoyne commented
Feature test to come in another PR, to follow.

2022-05-05 17:43 UTC, merged