[HOLD] Registration form csv
sul-dlss/argo pull request #3684
Opened 2022-05-11 19:38 UTC by justinlittman

## Why was this change made? 🤔
CSV are easier than forms.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

2022-05-11 22:55 UTC, ndushay commented
Will this ix #3611?

2022-05-12 11:14 UTC, justinlittman commented
The magic keyword is in the git commit for this PR.

2022-05-12 15:30 UTC, ndushay commented
> The magic keyword is in the git commit for this PR.

does that connect the PR to the issue on github and/or close the issue automagically?  If so ... wow!

2022-05-20 19:06 UTC, jcoyne requested changes

2022-05-20 19:06 UTC, jcoyne commented on app/forms/csv_registration_form.rb
> +  property :rights, virtual: true
This should be view/download/location/cdl.

2022-05-20 19:06 UTC, jcoyne commented on spec/features/item_registration_csv_spec.rb
> +      select 'Stanford', from: 'Rights'
The rights field no longer exists

2022-05-20 19:06 UTC, jcoyne commented on spec/features/item_registration_csv_spec.rb
> +      select 'Stanford', from: 'Rights'
The Rights field no longer exists.

2022-06-02 00:36 UTC, ndushay commented
@justinlittman gentle reminder that this PR is still open - I'm assuming it needs PO review, so I've assigned that label but I'm not sure if there is more to do here or not (it's a draft)

2022-06-02 10:56 UTC, justinlittman commented
This is part of the registration form redesign (#3653). @jcoyne how is this moving forward?

2022-06-21 19:10 UTC, ndushay commented
@jcoyne is this PR the combination of JLitt's work, and of your work in PR #3653?

2022-06-21 19:19 UTC, ndushay commented
Andrew reviewed this while reviewing PR #3653, so this has PO approval.

2022-06-21 20:16 UTC, ndushay commented
approved by Andrew.

2022-06-21 20:21 UTC, merged