Remove existing server.pid on startup when using docker
sul-dlss/argo pull request #3743
Opened 2022-06-15 00:24 UTC by aaron-collier

## Why was this change made? 🤔

This is a small docker file change to add an entrypoint script that will remove an existing `tmp/pids/server.pid` on startup because when running with foreman it is not removed on shutdown. When attached (watching the docker output) and ending with `ctrl-c` it remains, as well as when detached and running either `docker compose stop` or `docker compose down`. The result is that subsequent starts of the web application currently require manually removing the `server.pid` file to avoid the web container stopping with the `pid file already exists` error. 

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

2022-06-15 05:22 UTC, jcoyne requested changes

2022-06-15 05:22 UTC, jcoyne commented on Dockerfile
> +ENTRYPOINT ["docker/entrypoint.sh"]
Why entrypoint and not cmd? If the former, then we can't override this in docker-compose.yml

2022-06-15 16:04 UTC, ndushay approved these changes

2022-06-16 18:47 UTC, jcoyne approved these changes

2022-06-16 18:47 UTC, merged