add druid column to all exported structural metadata
sul-dlss/argo pull request #3768
Opened 2022-06-30 18:46 UTC by peetucket

## Why was this change made? 🤔

Fixes #3758 - include the druid column for all structural metadata exports (even single objects).

This adds the druid column to the core export class, and then removes it from the bulk action job (since it will come automatically from the single object now).

~~HOLD to validate on QA/stage with real data~~ validated on qa, works fine

## How was this change tested? 🤨

Updated/existing tests/localhost.  Verified on qa with actual data.

Note: existing spec for bulk action job is unchanged but passes, showing that it still works as expected (i.e. includes the druid column)

2022-06-30 18:46 UTC, peetucket commented on app/jobs/export_structural_job.rb
>        end
lines 14-18 above can be collapsed into one line, since now we don't need to add the druid specifically (it will come from the single object export)

2022-07-01 01:58 UTC, jcoyne requested changes
Did you test that the exported structural metadata was able to be imported again?

2022-07-01 03:19 UTC, ndushay commented
@andrewjbtw do you want to test this?

2022-07-01 18:52 UTC, peetucket commented
> Did you test that the exported structural metadata was able to be imported again?

I tested the single object exported structural metadata could be changed and re-imported with the new druid column.  This matches with what I see in the code, where the druid columns will just be ignored at import time.

The bulk action format has not changed (it always included the druid column).

I did update `spec/services/structure_updater_spec.rb` though so that the new column is used in the test.

2022-07-01 19:39 UTC, ndushay approved these changes

2022-07-01 22:14 UTC, peetucket commented
Unless Andrew wants to verify this upon his return and discovers an issue, it should be good to go without further work.

2022-07-05 14:53 UTC, jcoyne approved these changes

2022-07-05 16:50 UTC, merged

2022-07-05 17:14 UTC, ndushay commented
(Andrew indicated in slack that this doesn't require his approval).