Displaying error messsage with CSV uploads.
sul-dlss/argo pull request #3835
Opened 2022-08-26 14:53 UTC by lwrubel

## Why was this change made? 🤔

Fixes #3826. Displays an error when a CSV that raises CSV::MalformedCSVError uploaded. 

## How was this change tested? 🤨
Unit (and added unit test) and ran bulk action integration tests (`bulk_update_metadata` and `bulk_tags_edit`)

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

2022-08-26 16:38 UTC, jcoyne requested changes
@lwrubel can you rebase this. Currently it's 4 commits behind main. I wouldn't expect to see some of the Gemfile.lock changes in this PR.

2022-08-26 16:57 UTC, lwrubel commented
It's weird, I have rebased it, and was trying to figure out how to get Gemfile.lock out of the last commit. Will keep working on that. I also need to figure out why to diff-coverage went down.

2022-08-26 17:27 UTC, jcoyne commented
@lwrubel you must have done a `bundle update` and committed the result.  You should be able to remove `Gemfile.lock` from this commit.

2022-08-29 13:22 UTC, jcoyne approved these changes

2022-08-29 13:22 UTC, merged