deploy.rb: capistrano first deploy works without sprockets
sul-dlss/argo pull request #3844
Opened 2022-09-07 19:10 UTC by ndushay

## Why was this change made? 🤔

This fix made it possible to deploy the argo app to a newly built VM.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything this change breaks. ⚡

2022-09-07 19:52 UTC, jcoyne commented on config/deploy.rb
> +# configure capistrano-rails to work without sprockets
This is only necessary for the first deploy right? How do we ensure it gets turned off after?

2022-09-07 20:03 UTC, jcoyne requested changes
Could this be done by configuring 

```
    set :assets_manifests, -> {
        release_path.join("public", fetch(:assets_prefix), '.manifest.json')
    }
```

See https://github.com/capistrano/rails/issues/257

2022-09-07 21:07 UTC, ndushay commented
> set :assets_manifests, -> {
>         release_path.join("public", fetch(:assets_prefix), '.manifest.json')
>     }

I'll try it for the stage box rebuilds.

2022-09-07 22:05 UTC, ndushay commented
@jcoyne your suggestion didn't work.  :-(

2022-09-08 18:32 UTC, ndushay commented
@jcoyne and I paired and tweaked his suggestion.  It now works for the first deploy and for subsequent deploys.  Yay!

2022-09-08 18:45 UTC, jcoyne approved these changes

2022-09-08 18:45 UTC, merged