[HOLD] add header to registration report
sul-dlss/argo pull request #4130
Opened 2023-08-28 17:42 UTC by peetucket

# Why was this change made? 🤔

Maybe fixes #4104 -- just adds a header to the registration output to make it clear that barcode and folio instance HRID may be blank.

Copying and pasting the data into Excel or google sheets preserves the blank columns.

<img width="638" alt="Screen Shot 2023-08-28 at 10 25 58 AM" src="https://github.com/sul-dlss/argo/assets/47137/5434f987-7d3b-4cd9-be27-1b38a0e56b98">

# How was this change tested? 🤨

Localhost

2023-08-28 17:43 UTC, peetucket commented on app/views/registrations/create_status.html.erb
> +          <th>Source ID</th>
yes I know Symphony is dead (long live Folio), but this matches the pattern elsewhere which I presume we will rip out at once

2023-08-29 16:30 UTC, jmartin-sul requested changes
one nitpicky observation about HTML structure that i found after hunting through docs a little bit

2023-08-29 16:34 UTC, peetucket commented on app/views/registrations/create_status.html.erb
>        <% @registration_form.created.each do |dro| %>
Thanks - added the `tbody` element

2023-08-29 16:39 UTC, jmartin-sul approved these changes

2023-08-29 16:40 UTC, jmartin-sul approved these changes
feel free to merge when green -- CI seems to be taking its time to get started.

2023-08-29 16:52 UTC, merged